import React, { useState, useEffect } from 'react';
import './ComplianceDashboard.css';

interface ComplianceSummary {
  total_activities_30d: number;
  active_violations: number;
  active_alerts: number;
  avg_compliance_score: number;
  compliance_status: 'excellent' | 'good' | 'fair' | 'poor' | 'critical';
  last_updated: string;
}

interface Alert {
  id: string;
  alert_type: 'compliance_violation' | 'policy_breach' | 'risk_escalation' | 'system_alert';
  severity: 'low' | 'medium' | 'high' | 'critical';
  title: string;
  description: string;
  entity_type: string;
  entity_id: string;
  status: 'active' | 'acknowledged' | 'resolved';
  created_at: string;
  metadata: Record<string, any>;
}

interface ComplianceDashboardProps {
  enterpriseId: string;
}

export const ComplianceDashboard: React.FC<ComplianceDashboardProps> = ({ enterpriseId }) => {
  const [summary, setSummary] = useState<ComplianceSummary | null>(null);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadComplianceData();
  }, [enterpriseId]);

  const loadComplianceData = async () => {
    try {
      setLoading(true);
      // In a real implementation, you would call your API here
      // const summaryData = await fetchComplianceSummary(enterpriseId);
      // const alertsData = await fetchAlerts(enterpriseId);
      
      // Mock data for demonstration
      const mockSummary: ComplianceSummary = {
        total_activities_30d: 150,
        active_violations: 3,
        active_alerts: 5,
        avg_compliance_score: 87,
        compliance_status: 'good',
        last_updated: new Date().toISOString()
      };

      const mockAlerts: Alert[] = [
        {
          id: '1',
          alert_type: 'compliance_violation',
          severity: 'high',
          title: 'AI Disclosure Missing',
          description: 'Content generated by AI without proper disclosure',
          entity_type: 'agent_activity',
          entity_id: 'activity-123',
          status: 'active',
          created_at: new Date().toISOString(),
          metadata: { agent: 'content-generator-ai', action: 'generate_marketing_content' }
        },
        {
          id: '2',
          alert_type: 'policy_breach',
          severity: 'critical',
          title: 'Unauthorized Tool Usage',
          description: 'Tool not approved for use in this context',
          entity_type: 'agent_activity',
          entity_id: 'activity-124',
          status: 'active',
          created_at: new Date().toISOString(),
          metadata: { tool_name: 'unapproved-tool' }
        }
      ];

      setSummary(mockSummary);
      setAlerts(mockAlerts);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load compliance data');
    } finally {
      setLoading(false);
    }
  };

  const getComplianceStatusColor = (status: string) => {
    switch (status) {
      case 'excellent': return '#10B981';
      case 'good': return '#3B82F6';
      case 'fair': return '#F59E0B';
      case 'poor': return '#EF4444';
      case 'critical': return '#DC2626';
      default: return '#6B7280';
    }
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'low': return '#10B981';
      case 'medium': return '#F59E0B';
      case 'high': return '#EF4444';
      case 'critical': return '#DC2626';
      default: return '#6B7280';
    }
  };

  const acknowledgeAlert = async (alertId: string) => {
    try {
      // In a real implementation, you would call the API here
      // await acknowledgeAlertAPI(alertId);
      setAlerts(prev => prev.map(alert => 
        alert.id === alertId 
          ? { ...alert, status: 'acknowledged' as const }
          : alert
      ));
    } catch (err) {
      console.error('Failed to acknowledge alert:', err);
    }
  };

  const resolveAlert = async (alertId: string) => {
    try {
      // In a real implementation, you would call the API here
      // await resolveAlertAPI(alertId);
      setAlerts(prev => prev.map(alert => 
        alert.id === alertId 
          ? { ...alert, status: 'resolved' as const }
          : alert
      ));
    } catch (err) {
      console.error('Failed to resolve alert:', err);
    }
  };

  if (loading) {
    return (
      <div className="compliance-dashboard">
        <div className="loading">Loading compliance data...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="compliance-dashboard">
        <div className="error">Error: {error}</div>
      </div>
    );
  }

  return (
    <div className="compliance-dashboard">
      <div className="dashboard-header">
        <h2>Compliance Dashboard</h2>
        <div className="last-updated">
          Last updated: {summary?.last_updated ? new Date(summary.last_updated).toLocaleString() : 'Unknown'}
        </div>
      </div>

      {/* Compliance Summary Cards */}
      <div className="summary-cards">
        <div className="summary-card">
          <div className="card-title">Compliance Score</div>
          <div 
            className="card-value"
            style={{ color: getComplianceStatusColor(summary?.compliance_status || '') }}
          >
            {summary?.avg_compliance_score || 0}%
          </div>
          <div className="card-subtitle">{summary?.compliance_status || 'Unknown'}</div>
        </div>

        <div className="summary-card">
          <div className="card-title">Active Alerts</div>
          <div className="card-value">{summary?.active_alerts || 0}</div>
          <div className="card-subtitle">Require attention</div>
        </div>

        <div className="summary-card">
          <div className="card-title">Violations</div>
          <div className="card-value">{summary?.active_violations || 0}</div>
          <div className="card-subtitle">Policy breaches</div>
        </div>

        <div className="summary-card">
          <div className="card-title">Activities (30d)</div>
          <div className="card-value">{summary?.total_activities_30d || 0}</div>
          <div className="card-subtitle">Total monitored</div>
        </div>
      </div>

      {/* Alerts Section */}
      <div className="alerts-section">
        <h3>Recent Alerts</h3>
        <div className="alerts-list">
          {alerts.length === 0 ? (
            <div className="no-alerts">No active alerts</div>
          ) : (
            alerts.map(alert => (
              <div key={alert.id} className={`alert-item ${alert.status}`}>
                <div className="alert-header">
                  <div className="alert-title">{alert.title}</div>
                  <div 
                    className="alert-severity"
                    style={{ backgroundColor: getSeverityColor(alert.severity) }}
                  >
                    {alert.severity.toUpperCase()}
                  </div>
                </div>
                <div className="alert-description">{alert.description}</div>
                <div className="alert-meta">
                  <span className="alert-type">{alert.alert_type.replace('_', ' ')}</span>
                  <span className="alert-time">
                    {new Date(alert.created_at).toLocaleString()}
                  </span>
                </div>
                {alert.status === 'active' && (
                  <div className="alert-actions">
                    <button 
                      className="btn-acknowledge"
                      onClick={() => acknowledgeAlert(alert.id)}
                    >
                      Acknowledge
                    </button>
                    <button 
                      className="btn-resolve"
                      onClick={() => resolveAlert(alert.id)}
                    >
                      Resolve
                    </button>
                  </div>
                )}
              </div>
            ))
          )}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="quick-actions">
        <h3>Quick Actions</h3>
        <div className="action-buttons">
          <button className="btn-primary">Run Compliance Check</button>
          <button className="btn-secondary">View All Policies</button>
          <button className="btn-secondary">Generate Report</button>
        </div>
      </div>
    </div>
  );
};

export default ComplianceDashboard;
